workspace:
  base: /go
  path: src/github.com/journeymidnight/cropimage
pipeline:
  build:
    image: thesues/centos7-vips
    commands:
      - "bash build.sh"
  publish:
    image: plugins/docker
    repo:  thesues/cropimage
    secrets: [docker_username, docker_password]
    dockerfile: Dockerfile-alpine-runtime
  publish:
    image: plugins/docker
    repo:  thesues/openresty-cropimage
    secrets: [docker_username, docker_password]
    dockerfile: Dockerfile:openresty
