workspace:
  base: /go
  path: src/github.com/journeymidnight/cropimage
pipeline:
  build:
    image: thesues/centos7-vips
    commands:
      - "bash build.sh"
  publish-cropimage:
    image: plugins/docker
    repo:  thesues/cropimage
    secrets: [docker_username, docker_password]
    dockerfile: docker/Dockerfile-alpine-cropimage
  publish-openresty:
    image: plugins/docker
    repo:  thesues/openresty-cropimage
    secrets: [docker_username, docker_password]
    dockerfile: docker/Dockerfile-alpine-openresty
