version: '2'

services:
  redis:
    container_name: redis-cropimage
    image: "redis:alpine"
    networks:
      integrate_vpcbr:
        ipv4_address: "10.5.0.105"
  openresty:
    image: thesues/openresty-cropimage
    networks:
      integrate_vpcbr:
        ipv4_address: "10.5.0.102"
    ports:
      - 9001:80
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_SERVER=redis-cropimage
  cropimage2:
    networks:
      integrate_vpcbr:
        ipv4_address: "10.5.0.103"
    image: thesues/cropimage
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_SERVER=redis-cropimage
  cropimage1:
    networks:
      integrate_vpcbr:
        ipv4_address: "10.5.0.104"
    image: thesues/cropimage
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_SERVER=redis-cropimage

networks:
    integrate_vpcbr:
       external: true
